services:
  airflow-webserver:
    volumes:
      - ./dags:/opt/airflow/dags

  airflow-scheduler:
    volumes:
      - ./dags:/opt/airflow/dags

  airflow-dag-processor:
    volumes:
      - ./dags:/opt/airflow/dags
