#!/bin/bash

# Install Dashboard Options
# User dapat memilih Metabase, Superset, Grafana, atau Redash

echo "📊 DASHBOARD VISUALIZATION TOOLS"
echo "=================================="
echo ""
echo "Pilihan tools untuk visualisasi data:"
echo ""
echo "1️⃣  METABASE (Installed) ✅"
echo "    - Ease: ⭐⭐⭐⭐⭐ (Paling mudah)"
echo "    - Features: ⭐⭐⭐⭐"
echo "    - Port: 3000"
echo "    - Best for: Beginners, quick dashboards"
echo "    - Start: bash start_metabase.sh"
echo ""
echo "2️⃣  APACHE SUPERSET"
echo "    - Ease: ⭐⭐⭐⭐ (Advanced but powerful)"
echo "    - Features: ⭐⭐⭐⭐⭐ (Most features)"
echo "    - Port: 8088"
echo "    - Best for: Enterprise, complex visualizations"
echo "    - Install: bash install_superset.sh"
echo ""
echo "3️⃣  GRAFANA"
echo "    - Ease: ⭐⭐⭐⭐ (Easy for time-series)"
echo "    - Features: ⭐⭐⭐⭐"
echo "    - Port: 3001"
echo "    - Best for: Real-time monitoring, alerts"
echo "    - Install: bash install_grafana.sh"
echo ""
echo "4️⃣  REDASH"
echo "    - Ease: ⭐⭐⭐⭐ (Collaborative)"
echo "    - Features: ⭐⭐⭐⭐"
echo "    - Port: 5000"
echo "    - Best for: Team collaboration, query sharing"
echo "    - Install: bash install_redash.sh"
echo ""
echo "=================================="
echo ""
echo "📝 Recommended: Start dengan METABASE ✅"
echo "   - Paling mudah setup"
echo "   - UI paling user-friendly"
echo "   - Perfect untuk pemula"
echo ""
echo "🚀 Current Status:"
echo "   - Metabase: RUNNING (http://localhost:3000)"
echo "   - Airflow: RUNNING (http://localhost:8080)"
echo "   - PostgreSQL: RUNNING (127.0.0.1:5433)"
echo ""
